### ISSUE TITLE
能不能写一个wiki，如何使用此程序？

### ISSUE THREAD

**Issue by lukemin** [vpei/tvurl#1]
能不能写一个wiki，如何使用此程序？
大致看了一下是在青龙面板下运行的，但是报错
Traceback (most recent call last):
  File "/ql/data/scripts/vpei_tvurl/main.py", line 261, in <module>
    tvlists = json.load(f)
  File "/usr/local/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 185)

**Comment by vpei** [comment]
测试版，一直没有时间修复错误。

**Comment by lukemin** [comment]
> 测试版，一直没有时间修复错误。
如果可以的话，请修复一下吧。现在几位大神维护的源有很多不能用的。
